
'use strict';

var sUtil = require('../lib/util');
var autodesc = require('../lib/autodesc');

/**
 * The main router object
 */
var router = sUtil.router();

/**
 * The main application object reported when this module is require()d
 */
var app;

/**
 * GET http://hostname/description/{Title|Qnnn}
 * Gets an autogenerated description for the specified Q-number.
 */
router.get('/:title', function (req, res) {
    var params = {
        lang: "en"
    };
    var title = req.params.title;
    autodesc.ad.getDescription ( title , params , function ( qnum, text ) {
        var j = {
            q : qnum
        };
        if (undefined !== autodesc.wd.items[qnum]) {
            j.title = autodesc.wd.items[qnum].getLabel(params.lang);
            j.manual_description = autodesc.wd.items[qnum].getDesc(params.lang);
        }
        j.auto_description = text;
        res.status(200).json(j).end();
    });
});

module.exports = function (appObj) {
    app = appObj;
    return {
        path: '/description',
        skip_domain: true,
        api_version: 1,
        router: router
    };
};

