
'use strict';

var sUtil = require('../lib/util');
var autodesc = require('../lib/short_autodesc');

/**
 * The main router object
 */
var router = sUtil.router();

/**
 * The main application object reported when this module is require()d
 */
var app;

/**
 * GET {domain}/v1/description/{Qnn}
 * Gets an autogenerated description for the specified Q-number.
 */
router.get('/:qnum', function (req, res) {
    var params = {
        lang: "en"
    };
    var qnum = req.params.qnum;
    autodesc.ad.loadItem ( qnum , params , function ( text ) {
        var j = {
            q : qnum
        };
        if (undefined !== autodesc.wd.items[qnum]) {
            j.label = autodesc.wd.items[qnum].getLabel(params.lang);
            j.manual_description = autodesc.wd.items[qnum].getDesc(params.lang);
        }
        j.result = text;
        res.status(200).json(j).end();
    });
});

module.exports = function (appObj) {
    app = appObj;
    return {
        path: '/description',
        api_version: 1,
        router: router
    };
};

